# AFPM Analysis Configuration File
# This file controls matrix generation and analysis parameters

# Matrix Generation Settings
matrix_generation:
  # Matrix size configuration
  size_range:
    min_size: 4              # Minimum matrix size (must be >= 4)
    max_size: 65536          # Maximum matrix size (2^16)
    size_progression: "powers_of_2"  # Options: "powers_of_2", "linear", "custom"
    
    # For linear progression (if size_progression: "linear")
    step_size: 100           # Step size for linear progression
    
    # For custom progression (if size_progression: "custom")
    custom_sizes: [4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536]
  
  # Matrix types to generate
  matrix_types:
    - "tridiagonal_toeplitz"  # Standard [-1, 2, -1] pattern
    - "fem_poisson"          # FEM Poisson discretization
  
  # Statistical robustness
  matrices_per_size: 100      # Number of matrices to generate per size
  
  # Output directory
  output_dir: "test_matrices"
  
  # Random seed for reproducibility
  random_seed: 42

# AFPM Analysis Settings
afpm_analysis:
  # AFPM Configurations
  # Each configuration is a 9-element chromosome array
  # Values: -1 (exact), 0-99 (approximation percentage)
  # Index [0-7]: Mantissa bits 0-7, Index [8]: Most significant bit
  
  configurations:
    "Exact":
      chromosome: [-1, -1, -1, -1, -1, -1, -1, -1, -1]
      description: "Hardware exact multiplication"
      color: "#1f77b4"
      
    "Very Low Approx":
      chromosome: [20, 15, 10, 5, 0, 0, 0, 0, 0]
      description: "Approximate only least significant multiplications"
      color: "#ff7f0e"
      
    "Low Approximation":
      chromosome: [40, 30, 20, 10, 5, 0, 0, 0, 0]
      description: "Progressive approximation, preserve high bits"
      color: "#2ca02c"
      
    "Medium Approximation":
      chromosome: [60, 50, 40, 30, 20, 10, 5, 0, 0]
      description: "Balanced approximation across significance levels"
      color: "#d62728"
      
    "High Approximation":
      chromosome: [80, 70, 60, 50, 40, 30, 20, 10, 0]
      description: "Aggressive approximation, exact only most critical"
      color: "#9467bd"
      
    "Worst (chromo8=0)":
      chromosome: [99, 99, 99, 99, 99, 99, 99, 99, 0]
      description: "Maximum approximation, exact only AH×BH"
      color: "#8c564b"
  
  # Analysis settings
  results_dir: "results"
  
  # Error calculation settings
  error_metrics:
    - "relative_l2"          # Primary metric: ||x_afpm - x_exact||₂ / ||x_exact||₂
    - "absolute_l2"          # Secondary: ||x_afpm - x_exact||₂
    - "relative_inf"         # Optional: ||x_afpm - x_exact||∞ / ||x_exact||∞
  
  # Theoretical bounds
  theoretical_bounds:
    float32_epsilon: 1.19e-7  # 2^(-23)
    thomas_constant: 3.0      # Algorithm constant for Thomas method

# Plotting Settings
plotting:
  # Figure settings
  figure_size: [16, 12]      # Width, height in inches
  dpi: 300                   # Resolution for saved figures
  
  # Plot types to generate
  plot_types:
    - "logarithmic"          # Log-log scale plots
    # - "linear"               # Linear scale plots (disabled for performance)
    - "configuration_table"  # Configuration comparison table
  
  # Plot styling
  error_bars: true           # Show error bars (std deviation)
  grid: true                 # Show grid lines
  legend_fontsize: 8         # Legend font size
  
  # Color scheme (will use colors from configurations above)
  background_color: "white"
  grid_alpha: 0.3

# Advanced Settings
advanced:
  # Memory management
  max_memory_usage: "8GB"    # Maximum RAM usage estimation
  
  # Parallel processing
  enable_parallel: true     # Enable parallel matrix generation
  num_processes: 4           # Number of parallel processes
  
  # Numerical precision
  pivot_threshold: 1e-10     # Threshold for pivot detection
  condition_number_method: "svd"  # Options: "svd", "norm_estimate"
  
  # Error handling
  skip_failed_matrices: true  # Skip matrices that fail to solve
  verbose_output: true       # Detailed progress reporting

# Validation Settings
validation:
  # Matrix validation
  check_positive_definite: true    # Verify matrix properties
  check_condition_number: true     # Compute and validate condition numbers
  max_condition_number: 1e15       # Skip matrices with higher condition numbers
  
  # Result validation
  check_residual: true            # Verify Ax = b residual
  max_residual: 1e-10             # Maximum acceptable residual
  
  # Consistency checks
  compare_with_exact: true        # Compare AFPM with exact solver
  relative_tolerance: 1e-12       # Tolerance for exact comparison